"""
train_model.py

Ephemeral ML training and evaluation script generated by the pipeline.
Can be executed as a standalone training script:
    python train_model.py --config config.yaml --output_dir ./outputs
"""
import pandas as pd
import numpy as np
import yaml
import json
import os
import re
import argparse
from sklearn.model_selection import StratifiedKFold, KFold, RandomizedSearchCV
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score, mean_squared_error
from sklearn.ensemble import VotingClassifier, VotingRegressor
from xgboost import XGBClassifier, XGBRegressor
from lightgbm import LGBMClassifier, LGBMRegressor
from catboost import CatBoostClassifier, CatBoostRegressor
from sklearn.ensemble import HistGradientBoostingClassifier, HistGradientBoostingRegressor
from sklearn.base import clone
from tqdm import tqdm
from pathlib import Path

def load_config(config_path="config.yaml"):
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)
    repo_root = os.environ.get("REPO_ROOT", os.getcwd())
    if config.get("dataset_path") and not os.path.isabs(config.get("dataset_path")):
        config["dataset_path"] = os.path.join(repo_root, config["dataset_path"])
    if config.get("test_path") and not os.path.isabs(config.get("test_path")):
        config["test_path"] = os.path.join(repo_root, config["test_path"])
    return config

def engineer_features(df):
    df = df.copy()
    
    # 1. Basic Imputation
    if 'Embarked' in df.columns:
        df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
    if 'Fare' in df.columns:
        df['Fare'] = df['Fare'].fillna(df['Fare'].median())

    # 2. Extract Title and Name Length
    if 'Name' in df.columns:
        df['NameLength'] = df['Name'].apply(len)
        df['Title'] = df['Name'].astype(str).str.extract(r' ([A-Za-z]+)\.', expand=False)
        title_mapping = {
            "Mr": "Mr", "Miss": "Miss", "Mrs": "Mrs", "Master": "Master",
            "Mlle": "Miss", "Ms": "Miss", "Mme": "Mrs",
            "Don": "Rare", "Rev": "Rare", "Dr": "Rare", "Majeur": "Rare",
            "Lady": "Rare", "Sir": "Rare", "Col": "Rare", "Capt": "Rare",
            "Countess": "Rare", "Jonkheer": "Rare", "Dona": "Rare"
        } 
        df['Title'] = df['Title'].map(lambda x: title_mapping.get(x, 'Rare'))
        df = df.drop(columns=['Name'])

    # 3. Ticket Group Size and True Fare Per Person
    if 'Ticket' in df.columns:
        df['TicketGroupSize'] = df.groupby('Ticket')['Ticket'].transform('count')
        df['FarePerPerson'] = df['Fare'] / df['TicketGroupSize']
        df = df.drop(columns=['Ticket'])
    else:
        df['TicketGroupSize'] = 1
        df['FarePerPerson'] = df['Fare']

    # 4. Granular Age Imputation
    if 'Age' in df.columns and 'Title' in df.columns and 'Pclass' in df.columns and 'Sex' in df.columns:
        # Impute based on Class, Sex, and Title for maximum accuracy
        df['Age'] = df.groupby(['Pclass', 'Sex', 'Title'])['Age'].transform(lambda x: x.fillna(x.median()))
        # Fallback for any remaining NaNs
        df['Age'] = df['Age'].fillna(df.groupby('Title')['Age'].transform('median'))
        df['Age'] = df['Age'].fillna(df['Age'].median())
        
        # Women and Children Protocol Flag
        df['IsWomenOrBoy'] = ((df['Sex'] == 'female') | (df['Title'] == 'Master') | (df['Age'] <= 12)).astype(int)

    # 5. Consolidated Group Size
    if all(c in df.columns for c in ['SibSp', 'Parch']):
        df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
        # Use the maximum of family size or ticket group size to find true travel party size
        df['GroupSize'] = df[['FamilySize', 'TicketGroupSize']].max(axis=1)
        df['GroupCategory'] = pd.cut(df['GroupSize'], bins=[0, 1, 4, 20], labels=['Alone', 'Small', 'Large'])

    # 6. Cabin Deck Extraction
    if 'Cabin' in df.columns:
        df['HasCabin'] = df['Cabin'].notna().astype(int)
        df['Deck'] = df['Cabin'].apply(lambda x: str(x)[0] if pd.notna(x) else 'U')
        df['Deck'] = df['Deck'].replace(['T', 'A', 'G', 'F'], 'Rare')
        df = df.drop(columns=['Cabin'])

    # 7. Fare Bins (Using the normalized Fare Per Person)
    if 'FarePerPerson' in df.columns:
        df['FareBin'] = pd.qcut(df['FarePerPerson'], 4, labels=['Low', 'Med', 'High', 'VeryHigh'], duplicates='drop').astype(str)

    return df

def train_and_evaluate(config_path="config.yaml", output_dir="."):
    config = load_config(config_path)
    dataset_path = config.get("dataset_path")
    target_col = config.get("target_col")
    test_path = config.get("test_path")
    nrows = config.get("nrows", None)

    if not dataset_path or not target_col:
        raise ValueError("dataset_path and target_col must be specified in the config file.")

    df = pd.read_csv(dataset_path, nrows=nrows)
    
    if target_col not in df.columns:
        raise ValueError(f"Target column '{target_col}' not found in the dataset.")
    
    df_train = df.dropna(subset=[target_col])
    y_raw = df_train[target_col]
    X_raw = df_train.drop(columns=[target_col])

    X_raw.columns = [re.sub(r'[^\w\s]', '', col).replace(' ', '_') for col in X_raw.columns]
    
    # Preserve ID column
    id_col_name = None
    if X_raw.iloc[:, 0].nunique() == len(X_raw):
        potential_id_names = ['passengerid', 'id', 'index']
        if X_raw.columns[0].lower() in potential_id_names:
            id_col_name = X_raw.columns[0]
            X_raw = X_raw.drop(columns=[id_col_name])

    X = engineer_features(X_raw)

    task = 'classification' if y_raw.nunique() < 20 else 'regression'
    if task == 'classification':
        le_y = LabelEncoder()
        y = le_y.fit_transform(y_raw)
        scoring_fn_metric = roc_auc_score
        search_scoring = 'roc_auc'
    else:
        y = y_raw.values
        scoring_fn_metric = mean_squared_error
        search_scoring = 'neg_mean_squared_error'

    categorical_features = X.select_dtypes(include=['object', 'category']).columns.tolist()
    numerical_features = X.select_dtypes(include=np.number).columns.tolist()

    preprocessor = ColumnTransformer(
        transformers=[
            ('num', Pipeline([('scaler', StandardScaler())]), numerical_features),
            ('cat', Pipeline([('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))]), categorical_features)
        ],
        remainder='passthrough' 
    )

    # Initialize learner base estimators (Slightly boosted n_estimators for better learning)
    if task == 'classification':
        estimators = [
            ('xgb', XGBClassifier(n_estimators=300, random_state=42, n_jobs=-1, use_label_encoder=False, eval_metric='logloss')),
            ('lgb', LGBMClassifier(n_estimators=300, random_state=42, verbose=-1, n_jobs=-1)),
            ('cat', CatBoostClassifier(iterations=300, random_seed=42, verbose=0, thread_count=-1)),
            ('hist', HistGradientBoostingClassifier(max_iter=300, random_state=42))
        ]
        ensemble = VotingClassifier(estimators=estimators, voting='soft')
    else:
        estimators = [
            ('xgb', XGBRegressor(n_estimators=300, random_state=42, n_jobs=-1)),
            ('lgb', LGBMRegressor(n_estimators=300, random_state=42, verbose=-1, n_jobs=-1)),
            ('cat', CatBoostRegressor(iterations=300, random_seed=42, verbose=0, thread_count=-1)),
            ('hist', HistGradientBoostingRegressor(max_iter=300, random_state=42))
        ]
        ensemble = VotingRegressor(estimators=estimators)

    pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('model', ensemble)])

    # Refined Hyperparameter Search Space
    param_grid = {
        'model__xgb__max_depth': [3, 4, 5],
        'model__xgb__learning_rate': [0.03, 0.05, 0.1],
        'model__lgb__num_leaves': [15, 31, 45],
        'model__lgb__learning_rate': [0.03, 0.05, 0.1],
        'model__cat__depth': [4, 5, 6],
        'model__cat__learning_rate': [0.03, 0.05, 0.1]
    }

    # Wrap the pipeline in a RandomizedSearchCV (n_iter=10 for slightly deeper search)
    search = RandomizedSearchCV(
        pipeline, 
        param_distributions=param_grid, 
        n_iter=10, 
        cv=3, 
        scoring=search_scoring, 
        n_jobs=-1, 
        random_state=42
    )

    if task == 'classification':
        cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    else:
        cv = KFold(n_splits=5, shuffle=True, random_state=42)

    scores = []
    
    # Outer CV loop evaluating the Tuned Pipeline
    for fold, (train_idx, val_idx) in enumerate(tqdm(list(cv.split(X, y)), desc=f"Nested CV Progress")):
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y[train_idx], y[val_idx]

        fold_search = clone(search)
        try:
            fold_search.fit(X_train, y_train)
            best_model = fold_search.best_estimator_
            
            if task == 'classification':
                y_pred = best_model.predict_proba(X_val)[:, 1]
                score = scoring_fn_metric(y_val, y_pred)
            else:
                y_pred = best_model.predict(X_val)
                score = -scoring_fn_metric(y_val, y_pred) 
            scores.append(score)
        except Exception as e:
            print(f"Error during training/evaluation of fold {fold}: {e}")
            scores.append(np.nan)

    valid_scores = [s for s in scores if not np.isnan(s)]
    final_score = float(np.mean(valid_scores)) if valid_scores else 0.0
    
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    with open(out_dir / "metrics.json", "w") as f:
        json.dump({"cv_score": final_score}, f)

    if test_path and os.path.exists(test_path):
        print("Generating submission...")
        # Fit search on ALL training data to get the absolute best parameters
        search.fit(X, y)
        final_pipeline = search.best_estimator_

        test_df_raw = pd.read_csv(test_path, nrows=nrows)
        test_id_series = test_df_raw.iloc[:, 0].copy()
        test_id_column_name = test_df_raw.columns[0]

        test_df = test_df_raw.copy()
        test_df.columns = [re.sub(r'[^\w\s]', '', col).replace(' ', '_') for col in test_df.columns]

        if id_col_name and id_col_name in test_df.columns:
            test_X_raw = test_df.drop(columns=[id_col_name])
        elif test_id_column_name in test_df.columns: 
             test_X_raw = test_df.drop(columns=[test_id_column_name])
        else: 
             test_X_raw = test_df 

        if target_col in test_X_raw.columns:
            test_X_raw = test_X_raw.drop(columns=[target_col])

        test_X = engineer_features(test_X_raw)

        # Align columns
        missing_cols_in_test = set(X.columns) - set(test_X.columns)
        for c in missing_cols_in_test:
            test_X[c] = 0 
        test_X = test_X[X.columns]

        if task == 'classification':
            preds = final_pipeline.predict_proba(test_X)[:, 1]
        else:
            preds = final_pipeline.predict(test_X)

        submission = pd.DataFrame()
        submission[test_id_column_name] = test_id_series.values 
        submission[target_col] = preds
        submission.to_csv(out_dir / "raw_submission.csv", index=False)
        print("Saved raw_submission.csv")

    return final_score

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=str, default="config.yaml", help="Path to config file")
    parser.add_argument("--output_dir", type=str, default=".", help="Directory to save outputs")
    args = parser.parse_args()
    
    os.makedirs(args.output_dir, exist_ok=True)
    
    train_and_evaluate(args.config, args.output_dir)