"""
train_model.py

Ephemeral ML training and evaluation script generated by the pipeline.
Can be executed as a standalone training script:
    python train_model.py --config config.yaml --output_dir ./outputs
"""
import pandas as pd
import numpy as np
import yaml
import json
import os
import re
import argparse
from pathlib import Path
from sklearn.model_selection import StratifiedKFold, KFold
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score, mean_squared_error
from sklearn.ensemble import VotingClassifier, VotingRegressor
from xgboost import XGBClassifier, XGBRegressor
from lightgbm import LGBMClassifier, LGBMRegressor
from catboost import CatBoostClassifier, CatBoostRegressor
from sklearn.linear_model import RidgeClassifier, Ridge
from sklearn.base import clone
from tqdm import tqdm
import warnings

warnings.filterwarnings('ignore')

def load_config(config_path="config.yaml"):
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)
    repo_root = os.environ.get("REPO_ROOT", os.getcwd())
    if config.get("dataset_path") and not os.path.isabs(config.get("dataset_path")):
        config["dataset_path"] = os.path.join(repo_root, config["dataset_path"])
    if config.get("test_path") and not os.path.isabs(config.get("test_path")):
        config["test_path"] = os.path.join(repo_root, config["test_path"])
    return config

def train_and_evaluate(config_path="config.yaml", output_dir="."):
    # 1. Load Data
    config = load_config(config_path)
    dataset_path = config.get("dataset_path")
    target_col = config.get("target_col")
    test_path = config.get("test_path")

    df = pd.read_csv(dataset_path)
    df = df.dropna(subset=[target_col])
    y_raw = df[target_col]
    X = df.drop(columns=[target_col])
    
    # Clean feature names
    X.columns = [re.sub(r'[^\w\s]', '', col).replace(' ', '_') for col in X.columns]
    
    # 2. Determine Task & Encode Target
    task = 'classification' if y_raw.nunique() < 20 else 'regression'
    if task == 'classification':
        le_y = LabelEncoder()
        y = le_y.fit_transform(y_raw)
    else:
        y = y_raw.values

    # 3. Build Preprocessor
    categorical_features = X.select_dtypes(include=['object', 'category']).columns.tolist()
    numerical_features = X.select_dtypes(include=np.number).columns.tolist()

    preprocessor = ColumnTransformer(
        transformers=[
            ('num', StandardScaler(), numerical_features),
            ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_features)
        ],
        remainder='passthrough'
    )

    # 4. Initialize Models (Minimal Parameters)
    if task == 'classification':
        estimators = [
            ('xgb', XGBClassifier(random_state=42, n_jobs=-1, eval_metric='logloss')),
            ('lgb', LGBMClassifier(random_state=42, n_jobs=-1, verbose=-1)),
            ('cat', CatBoostClassifier(random_state=42, verbose=0, thread_count=-1)),
            ('ridge', RidgeClassifier(random_state=42))
        ]
        # Soft voting requires predict_proba, but RidgeClassifier doesn't support it natively.
        # We drop ridge for soft voting, or use hard voting. Soft is better for AUC.
        ensemble_estimators = [e for e in estimators if e[0] != 'ridge']
        ensemble = VotingClassifier(estimators=ensemble_estimators, voting='soft')
        cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
        scoring_fn = roc_auc_score
    else:
        estimators = [
            ('xgb', XGBRegressor(random_state=42, n_jobs=-1)),
            ('lgb', LGBMRegressor(random_state=42, n_jobs=-1, verbose=-1)),
            ('cat', CatBoostRegressor(random_state=42, verbose=0, thread_count=-1)),
            ('ridge', Ridge(random_state=42))
        ]
        ensemble = VotingRegressor(estimators=estimators)
        cv = KFold(n_splits=5, shuffle=True, random_state=42)
        scoring_fn = mean_squared_error

    pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                               ('model', ensemble)])
    
    # 5. Cross-Validation
    print("Running 5-Fold CV...")
    scores = []
    for train_idx, val_idx in tqdm(list(cv.split(X, y)), desc="CV"):
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y[train_idx], y[val_idx]
        
        fold_pipeline = clone(pipeline)
        fold_pipeline.fit(X_train, y_train)
        
        if task == 'classification':
            y_pred = fold_pipeline.predict_proba(X_val)[:, 1]
            score = scoring_fn(y_val, y_pred)
        else:
            y_pred = fold_pipeline.predict(X_val)
            score = -scoring_fn(y_val, y_pred)
        scores.append(score)

    final_score = float(np.mean(scores))
    print(f"Final CV Score: {final_score:.4f}")
    
    os.makedirs(output_dir, exist_ok=True)
    with open(os.path.join(output_dir, "metrics.json"), "w") as f:
        json.dump({"cv_score": final_score}, f)

    # 6. Generate Submission
    if test_path and os.path.exists(test_path):
        print("Generating submission...")
        pipeline.fit(X, y)
        test_df = pd.read_csv(test_path)
        
        test_X = test_df[X.columns.intersection(test_df.columns)]
        test_X = test_X.reindex(columns=X.columns, fill_value=0)

        if task == 'classification':
            preds = pipeline.predict_proba(test_X)[:, 1]
        else:
            preds = pipeline.predict(test_X)
            
        submission = pd.DataFrame()
        if len(test_df.columns) > 0:
             submission[test_df.columns[0]] = test_df.iloc[:, 0]
        submission[target_col] = preds
        submission.to_csv(os.path.join(output_dir, "raw_submission.csv"), index=False)

    return final_score

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=str, default="config.yaml", help="Path to config file")
    parser.add_argument("--output_dir", type=str, default=".", help="Directory to save outputs")
    args = parser.parse_args()
    train_and_evaluate(args.config, args.output_dir)